# Generated by Django 5.0.3 on 2024-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', '여자'), ('1', '남자'), ('2', '트렌스젠더'), ('3', '논바이너리'), ('4', '밝히지 않음')], default=4, max_length=10, verbose_name='성별'),
        ),
    ]
