# Generated by Django 5.0.3 on 2024-03-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_date_board_likes_board_reviews_board_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(default='mobbom', max_length=30),
        ),
    ]
